version: '3'
services:

  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"
    expose:
      - 6379
    environment:
      - POLL_HOSTNAME=poll
      - WORKER_HOSTNAME=worker
    networks:
      - poll-tier
      - back-tier

  db:
    image: postgres:9.4
    restart: on-failure
    networks:
      - result-tier
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

  poll:
    build: ./poll
    restart: on-failure
    environment:
      - REDIS_ADDRESS=redis
    ports:
      - "5000:80"
    networks:
      - poll-tier
    depends_on:
      - redis

  result: 
    build: ./result
    restart: on-failure
    environment:
      - HOSTNAME=db
      - PORT=80
    networks:
      - result-tier
    depends_on:
      - db
    ports:
      - 5001:80

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    restart: on-failure

    environment:
      - REDIS_HOSTNAME=redis
      - HOSTNAME=db
      - PASSWORD=password
      - USER=postgres

    networks:
      - back-tier
    ports:
      - 5002:80


volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: